/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package tests.infrastructure;

public interface jwtListenerService {

org.softauto.tester.Listener com_cassiomolin_example_security_api_model_AuthenticationToken_setToken() throws Exception;
}