/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package tests.infrastructure;

public interface jwtService {

org.softauto.tester.Step com_cassiomolin_example_greeting_api_resource_GreetingResource_getPublicGreeting() throws Exception;

org.softauto.tester.Step com_cassiomolin_example_greeting_api_resource_GreetingResource_getProtectedGreeting() throws Exception;

org.softauto.tester.Step com_cassiomolin_example_security_api_resource_AuthenticationResource_authenticate(com.cassiomolin.example.security.api.model.UserCredentials credentials  ) throws Exception;

org.softauto.tester.Step com_cassiomolin_example_security_api_resource_AuthenticationResource_refresh() throws Exception;

org.softauto.tester.Step com_cassiomolin_example_user_api_resource_UserResource_getUsers() throws Exception;

org.softauto.tester.Step com_cassiomolin_example_user_api_resource_UserResource_getUser(Long userId  ) throws Exception;

org.softauto.tester.Step com_cassiomolin_example_user_api_resource_UserResource_getAuthenticatedUser() throws Exception;

org.softauto.tester.Step com_cassiomolin_example_user_service_UserService_findByUsernameOrEmail(String identifier  ) throws Exception;

org.softauto.tester.Step com_cassiomolin_example_user_service_UserService_findAll() throws Exception;

org.softauto.tester.Step com_cassiomolin_example_user_service_UserService_findById(Long userId  ) throws Exception;

public interface Callback extends jwtService {
org.softauto.tester.Step  com_cassiomolin_example_greeting_api_resource_GreetingResource_getPublicGreeting(  org.apache.avro.ipc.CallFuture<javax.ws.rs.core.Response> callback) throws java.io.IOException;

org.softauto.tester.Step  com_cassiomolin_example_greeting_api_resource_GreetingResource_getProtectedGreeting(  org.apache.avro.ipc.CallFuture<javax.ws.rs.core.Response> callback) throws java.io.IOException;

org.softauto.tester.Step  com_cassiomolin_example_security_api_resource_AuthenticationResource_authenticate(com.cassiomolin.example.security.api.model.UserCredentials credentials   ,org.apache.avro.ipc.CallFuture<javax.ws.rs.core.Response> callback) throws java.io.IOException;

org.softauto.tester.Step  com_cassiomolin_example_security_api_resource_AuthenticationResource_refresh(  org.apache.avro.ipc.CallFuture<javax.ws.rs.core.Response> callback) throws java.io.IOException;

org.softauto.tester.Step  com_cassiomolin_example_user_api_resource_UserResource_getUsers(  org.apache.avro.ipc.CallFuture<javax.ws.rs.core.Response> callback) throws java.io.IOException;

org.softauto.tester.Step  com_cassiomolin_example_user_api_resource_UserResource_getUser(Long userId   , org.apache.avro.ipc.CallFuture<javax.ws.rs.core.Response> callback) throws java.io.IOException;

org.softauto.tester.Step  com_cassiomolin_example_user_api_resource_UserResource_getAuthenticatedUser(  org.apache.avro.ipc.CallFuture<javax.ws.rs.core.Response> callback) throws java.io.IOException;

org.softauto.tester.Step  com_cassiomolin_example_user_service_UserService_findByUsernameOrEmail(String identifier   , org.apache.avro.ipc.CallFuture<com.cassiomolin.example.user.domain.Person> callback) throws java.io.IOException;

org.softauto.tester.Step  com_cassiomolin_example_user_service_UserService_findAll(  org.apache.avro.ipc.CallFuture<java.util.List> callback) throws java.io.IOException;

org.softauto.tester.Step  com_cassiomolin_example_user_service_UserService_findById(Long userId   , org.apache.avro.ipc.CallFuture<java.util.Optional> callback) throws java.io.IOException;


    }
}




