/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.softauto.listener.system;

import com.google.inject.AbstractModule;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.softauto.core.Configuration;
import org.softauto.core.Context;
import org.softauto.core.Utils;


@org.apache.avro.specific.AvroGenerated
public class BasicModule extends AbstractModule {

    private static Logger logger = LogManager.getLogger(BasicModule.class);

    private Class getListenerServiceLogImplClass() {
        return Utils.getClazz(Configuration.get(Context.TEST_INFRASTRUCTURE_PATH).asText() +"/ListenerServiceLogImpl");
    }

    private Class getListenerServiceImplClass() throws Exception{
        return Utils.getClazz(Configuration.get(Context.TEST_INFRASTRUCTURE_PATH).asText() + "/ListenerServiceImpl");
    }

    @Override
    protected void configure() {
    try{
        bind(SystemServiceImpl.class);
        bind(getListenerServiceLogImplClass()).toInstance(getListenerServiceLogImplClass().newInstance());
        bind(getListenerServiceImplClass()).toInstance(getListenerServiceImplClass().newInstance());
    }catch(Exception e){
        e.printStackTrace();
    }
  }
}