/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.softauto.tester;


import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.softauto.plugin.ProviderManager;
import org.softauto.plugin.ProviderScope;
import org.softauto.plugin.spi.PluginProvider;


@org.apache.avro.specific.AvroGenerated
public class AbstractTesterImpl {

    private static final Logger logger = LogManager.getLogger(AbstractTesterImpl.class);



    public AbstractTesterImpl(){
        try {
           //Log.set(LEVEL_TRACE);
           SystemState.getInstance().initialize();
           loadPlugins();
        }catch (Exception e){
            logger.error("fail start listener ",e);
        }
    }



    public  void loadPlugins(){
        try {
            for(PluginProvider provider : ProviderManager.providers(ProviderScope.Tester)){
                  provider.create().initialize().register();
            }
        }catch (Exception e){
            logger.error("fail to load plugins  ",e);
        }
    }

}