---
serializer_port: "8085"
listener_port: "9091"
serializer_host: "localhost"
tests_infrastructure_path: "C:/work/myprojects/java/jdry/examples/cucumberExampleTests/target/classes/tests/infrastructure"
#log
log_level: "trace"



