/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.softauto.grpc.system;

import com.google.inject.AbstractModule;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.softauto.guice.InitializeNoParamProvider;

@org.apache.avro.specific.AvroGenerated
public class BasicModule extends AbstractModule {

    private static Logger logger = LogManager.getLogger(BasicModule.class);

    @Override
    protected void configure() {
    try{
        bind(org.softauto.grpc.system.SystemServiceImpl.class).toInstance(org.softauto.grpc.system.SystemServiceImpl.getInstance());
    }catch(Exception e){
        e.printStackTrace();
    }
  }
}